/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dueños.Vista;

/**
 *
 * @author Usuario
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        species = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        race = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sex = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        micro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        photo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tattoo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ido = new javax.swing.JTextField();
        addpet = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ida = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dates = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        hour = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        process = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        reason = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        idow = new javax.swing.JTextField();
        addpo = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD");

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\descarga-removebg-preview.png")); // NOI18N
        jLabel23.setText("jLabel23");

        back.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setText("Add Pets");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel3.setText("Id pets");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        idp.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 102, 24));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 59, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 102, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel5.setText("Species");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 64, -1));

        species.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        species.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciesActionPerformed(evt);
            }
        });
        getContentPane().add(species, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 102, 21));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel6.setText("Race");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 37, -1));

        race.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(race, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 102, 21));

        age.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 102, 21));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel8.setText("Date_of_birth");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        date.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 102, 21));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel9.setText("Sex");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 37, -1));

        sex.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 107, 24));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel10.setText("Microchip");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        micro.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(micro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 107, 24));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel11.setText("Photo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 58, -1));

        photo.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 107, 21));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel12.setText("Tattoo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));
        getContentPane().add(tattoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 107, 21));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel13.setText("Id Owner");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        ido.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(ido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 107, 21));

        addpet.setBackground(new java.awt.Color(153, 153, 255));
        addpet.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        addpet.setForeground(new java.awt.Color(255, 255, 255));
        addpet.setText("Add Pet");
        getContentPane().add(addpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel14.setText("Add Appointments");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        ida.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(ida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 104, 24));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel16.setText("Date");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 43, -1));

        dates.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 102, 22));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel17.setText("Hour");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 43, -1));

        jLabel18.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel18.setText("Age");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 43, -1));

        hour.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 102, 22));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel7.setText("State");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 49, -1));

        state.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 102, 21));

        jLabel19.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel19.setText("Process");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        process.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(process, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 102, 21));

        jLabel20.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel20.setText("Reason");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 64, -1));

        reason.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 102, 24));

        jLabel21.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel21.setText("Id Owner");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        idow.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        getContentPane().add(idow, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 102, 21));

        addpo.setBackground(new java.awt.Color(153, 153, 255));
        addpo.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        addpo.setForeground(new java.awt.Color(255, 255, 255));
        addpo.setText("Add");
        addpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpoActionPerformed(evt);
            }
        });
        getContentPane().add(addpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel22.setText("Id Appointment");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void speciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speciesActionPerformed

    private void addpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addpoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addpet;
    private javax.swing.JButton addpo;
    public javax.swing.JTextField age;
    public javax.swing.JButton back;
    public javax.swing.JTextField date;
    public javax.swing.JTextField dates;
    public javax.swing.JTextField hour;
    public javax.swing.JTextField ida;
    public javax.swing.JTextField ido;
    public javax.swing.JTextField idow;
    public javax.swing.JTextField idp;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField micro;
    public javax.swing.JTextField photo;
    public javax.swing.JTextField process;
    public javax.swing.JTextField race;
    public javax.swing.JTextField reason;
    public javax.swing.JTextField sex;
    public javax.swing.JTextField species;
    public javax.swing.JTextField state;
    public javax.swing.JTextField tattoo;
    // End of variables declaration//GEN-END:variables
}
