/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctors.Vista;

/**
 *
 * @author Usuario
 */
public class Vista_Doctors extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Doctors
     */
    public Vista_Doctors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        password1 = new javax.swing.JTextField();
        inicio = new javax.swing.JButton();
        ids = new javax.swing.JLabel();
        pas = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        view = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        id2 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        espe = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        information = new javax.swing.JTextArea();
        names = new javax.swing.JTextField();
        species = new javax.swing.JTextField();
        micro = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        date_of = new javax.swing.JTextField();
        photo = new javax.swing.JTextField();
        id_owners = new javax.swing.JTextField();
        race = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        tatto = new javax.swing.JTextField();
        doctor = new javax.swing.JLabel();
        pets = new javax.swing.JLabel();
        patitas = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(208, 251, 208));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctors");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, -1));

        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, 20));

        password1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel1.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 100, 20));

        inicio.setBackground(new java.awt.Color(151, 216, 151));
        inicio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        inicio.setText("Inicio sesión");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        panel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        ids.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        ids.setText("ID:");
        panel1.add(ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 40, -1));

        pas.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        pas.setText("PASSWORD");
        panel1.add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        panel2.setBackground(new java.awt.Color(208, 251, 208));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(151, 216, 151));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        update.setBackground(new java.awt.Color(151, 216, 151));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        panel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        view.setBackground(new java.awt.Color(151, 216, 151));
        view.setText("View");
        panel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        clean.setBackground(new java.awt.Color(151, 216, 151));
        clean.setText("Clean");
        panel2.add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        id2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id2ActionPerformed(evt);
            }
        });
        panel2.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 71, -1));

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        panel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 71, -1));

        espe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(espe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 71, -1));

        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 71, -1));

        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 71, -1));

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 71, -1));

        information.setColumns(20);
        information.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        information.setRows(5);
        jScrollPane1.setViewportView(information);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, 210));

        names.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(names, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 77, -1));

        species.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(species, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 77, -1));

        micro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(micro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 77, -1));

        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 77, -1));

        date_of.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(date_of, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 77, -1));

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });
        panel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 77, -1));

        id_owners.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(id_owners, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 77, -1));

        race.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        race.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raceActionPerformed(evt);
            }
        });
        panel2.add(race, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 77, -1));

        sex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 159, 94)));
        panel2.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 77, -1));
        panel2.add(tatto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 77, 20));

        doctor.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        doctor.setText("Update doctor");
        panel2.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pets.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pets.setForeground(new java.awt.Color(51, 0, 51));
        pets.setText("Add pets");
        panel2.add(pets, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, -1));

        patitas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        patitas.setText("VETERINARIA PATITAS FELICES");
        panel2.add(patitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoActionPerformed

    private void raceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raceActionPerformed

    private void id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id2ActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Doctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField age;
    public javax.swing.JButton clean;
    public javax.swing.JTextField date_of;
    public javax.swing.JLabel doctor;
    public javax.swing.JTextField email;
    public javax.swing.JTextField espe;
    public javax.swing.JTextField id;
    public javax.swing.JTextField id2;
    public javax.swing.JTextField id_owners;
    public javax.swing.JLabel ids;
    public javax.swing.JTextArea information;
    public javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField micro;
    public javax.swing.JTextField name;
    public javax.swing.JTextField names;
    public javax.swing.JPanel panel1;
    public javax.swing.JPanel panel2;
    public javax.swing.JLabel pas;
    public javax.swing.JTextField password;
    public javax.swing.JTextField password1;
    public javax.swing.JLabel patitas;
    public javax.swing.JLabel pets;
    public javax.swing.JTextField phone;
    public javax.swing.JTextField photo;
    public javax.swing.JTextField race;
    public javax.swing.JTextField sex;
    public javax.swing.JTextField species;
    public javax.swing.JTextField tatto;
    public javax.swing.JButton update;
    public javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
