/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrator.Vista;

import java.awt.print.*;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Vista_Invoice extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Vista_Invoice
     */
    public Vista_Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(153, 153, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Veterinaria patitas felices");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Av 33 calle 32 Barrio Belen");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1024589654");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 36, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("313258974");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 103, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel5.setText("Name");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel6.setText("Address");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel7.setText("NIT");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 6, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel8.setText("Telefono");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 73, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\Invoice\\src\\invoice\\Vista\\imagen\\patitas feclices (1).png")); // NOI18N
        jLabel19.setText("jLabel19");
        panel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 197, 180));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 17)); // NOI18N
        jLabel10.setText("Invoice");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 172, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel11.setText("Quantity");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 212, -1, -1));
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 256, 91, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel12.setText("Products");
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        panel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 91, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel13.setText("Unit Value");
        panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));
        panel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 91, -1));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel14.setText("Total");
        panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 43, -1));
        panel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 91, -1));
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 304, 91, -1));
        panel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 91, -1));
        panel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 91, -1));
        panel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 91, -1));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel16.setText("Subtotal");
        panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        panel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 91, -1));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel17.setText("Impuesto");
        panel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 401, 70, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        panel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 91, -1));

        jLabel18.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel18.setText("Total");
        panel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 43, -1));
        panel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 91, -1));

        jToggleButton1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jToggleButton1.setText("Generar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\Invoice\\src\\invoice\\Vista\\imagen\\Logo_vet__-removebg-preview (1).png")); // NOI18N
        jLabel9.setText("jLabel9");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 341, 452, 324));

        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jLabel15.setText("45b33fda-cb18-88f1-7ct6");
        panel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        double  vup1, vup2, vtp1, vtp2, subtotal, igv, preciototal;
        String pro1, pro2;
        
        pro1 =jTextField3.getText();
        pro2 = jTextField4.getText();
        vup1 = Double.parseDouble(jTextField5.getText());
        vup2 = Double.parseDouble(jTextField6.getText());
        
        int cantidad1 = Integer.parseInt(jTextField2.getText());
        int cantidad = Integer.parseInt(jTextField1.getText());
        vup1 = Double.parseDouble(jTextField5.getText());
        double total1 = cantidad * vup1;
        double total2 = cantidad1 * vup2;
        subtotal = total1 + total2;
        double IGV = subtotal * 19;
        preciototal = IGV;

        jTextField11.setText(preciototal + "");
        jTextField10.setText(IGV + "");
        jTextField9.setText(subtotal + "");
        jTextField7.setText(total1 + "");
        jTextField8.setText(total2 + "");
        
        
        if (subtotal > 0 && IGV > 0 && preciototal > 0) {
            JOptionPane.showMessageDialog(null, "Invoice generated successfully", "Successfully", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Error when generating the invoice", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();
            if (top) {
                gap.print();
            }
        }
        catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Program error", "Error\n" + e, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    public javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if (index > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
        hub.scale(0.7, 0.7);
        panel1.printAll(graf);
        return PAGE_EXISTS;
    }
}
